### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by JavascriptLearner815**
Contributor Covenant Code of Conduct to start the project.

### CODE REVIEW

**Comment by timmy61109** [comment]
Sorry to see it so late, I have been busy recently, I will find a way to help you finish it this week

**Comment by timmy61109** [comment]
I think this should be possible at the moment, and I will write more details when the project is determined in which direction to go.

**Review by timmy61109 — APPROVED** [review]
我覺得目前可以，就因為也不知道目前這個專案要往什麼方向前進。

I think it can be done at the moment, just because I don't know where the current project is going.

**Comment by JavascriptLearner815** [comment]
Commits need to have verified signatures, as a quick note. If you don't have verified signatures turned on yet, you can learn how on this page:

https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification

And to connect using SSH (so you don't need to use your username and password), you can learn how to do that on this page:

https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by timmy61109** [comment]
> Commits need to have verified signatures, as a quick note. If you don't have verified signatures turned on yet, you can learn  how on this page:
>
> https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification
>
> And to connect using SSH (so you don't need to use your username and password), you can learn how to do that on this page:
>
> https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

Okay, got it, I will finish it later, it will take a while

**Pull request merged**
