### PR TITLE
Add more workflows

### PR DESCRIPTION
**Pull request by JavascriptLearner815**
In this pull request we will expand on #4 and add more than just one workflow to the project.

### CODE REVIEW

**Review by timmy61109 — APPROVED** [review]
This should just be a demonstration that he can run and operate the check, right?

**Comment by JavascriptLearner815** [comment]
> This should just be a demonstration that he can run and operate the check, right?

I believe you're talking about the greeting workflow. It is for that purpose.

If my belief is correct, then the comment was also misplaced in #6.

**Comment by timmy61109** [comment]
> > This should just be a demonstration that he can run and operate the check, right?
> 
> I believe you're talking about the greeting workflow. It is for that purpose.
> 
> If my belief is correct, then the comment was also misplaced in #6.

It looks like a greeting process, but currently this greeting process seems to be displayed only in GitHub Actions, that is, only in CI.

Will it be deployed directly in the domain of `.github.io` after the check is completed.

**Comment by JavascriptLearner815** [comment]
> > > This should just be a demonstration that he can run and operate the check, right?
> > 
> > 
> > I believe you're talking about the greeting workflow. It is for that purpose.
> > If my belief is correct, then the comment was also misplaced in #6.
> 
> It looks like a greeting process, but currently this greeting process seems to be displayed only in GitHub Actions, that is, only in CI.
> 
> Will it be deployed directly in the domain of `.github.io` after the check is completed.

Short answer: No.

<details>
<summary>Long answer</summary>
The "greeting" manual test action is only meant for CI, same with the other workflows. 

I will explicitly create code in the `/docs` folder itself to create things for the website.

**Comment by timmy61109** [comment]
> > > > This should just be a demonstration that he can run and operate the check, right?
> > > 
> > > 
> > > I believe you're talking about the greeting workflow. It is for that purpose.
> > > If my belief is correct, then the comment was also misplaced in #6.
> > 
> > 
> > It looks like a greeting process, but currently this greeting process seems to be displayed only in GitHub Actions, that is, only in CI.
> > Will it be deployed directly in the domain of `.github.io` after the check is completed.
> 
> Short answer: No.
> 
> Long answer
> The "greeting" manual test action is only meant for CI, same with the other workflows.
> I will explicitly create code in the `/docs` folder itself to create things for the website.

Ok, I know.

**Review by timmy61109 — COMMENTED** [review]
Ok, Maybe wait for this project to be completed slowly, I can know what this project is going to do

**Review by timmy61109 — DISMISSED** [review]

**Review by timmy61109 — COMMENTED** [review]
This is not supposed to have been merged, so if there is any content in this merge request that needs to be merged, you may be able to mention it a little bit.

**Review by Androz2091 — DISMISSED** [review]

**Review by timmy61109 — DISMISSED** [review]

**Review by timmy61109 — APPROVED** [review]

**Pull request merged**
